version: "3"
services: 
    shorturl:
        build: .
        image: shorturl:latest
        ports:
            - "8080:8080"
        depends_on:
            - aerospike
    aerospike:
        image: aerospike/aerospike-server
        ports: 
            - "3000:3000"
            - "3001:3001"
            - "3002:3002"
            - "3003:3003"
networks:
    default:
        external:
            name: shorturl-network